manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: pa-cotte
      url-base: https://github.com/pa-cotte

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.7.0
